---
title: "Practical Machine Learning. Prediction Assignment"
author: "Sergey Bogdanov"
date: 'Feb 20, 2019'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr); library(caret); library(data.table); library(lubridate)
```

## Abstract



## Read data ann clean data

```{r}
pml_training <- read_csv("pml-training.csv"); pml_testing <- read_csv("pml-testing.csv")

# Remove text "#DIV/0!"
for (i in names(pml_training)) {
    t<-  pml_training[,i]
    t[t == "#DIV/0!"] <- NA
    pml_training[,i] <- t
}
# Remove empty varibales 
t<- apply(pml_training, 2, function(X) mean(!is.na(X)*1) ) > 0.0
pml_training <- pml_training[t]

# Some rows (new_window == yes) have aggregates for the windows. 
# Testing dataset have only raw data variables filled, that why we can remove 
# all empty variables of test data from training data.

# Descriptors and timestamps: names(pml_training[, 1:7])
# Raw data:
t<- apply(pml_training, 2, function(X) mean(!is.na(X)*1) ) > 0.05
training_raw <- as.data.table(pml_training[t])

# Aggregates $ statistics:
training_stat <- as.data.table( cbind(pml_training[,1:7], pml_training[!t]) ) 
training_stat <- training_stat[rowSums(is.na(training_stat[,8:ncol(training_stat)])) != ncol(training_stat)-7, ]

# There is only raw data in testing dataset, so we use this variables in training dataset. 
 
# Model development
    # Разбить на тестовую и тренировочную выборку
inTrain <- createDataPartition(y=training_raw$classe, p=0.60, list=FALSE)
# subset spam data to training
training <- training_raw[inTrain,]
# subset spam data (the rest) to test
testing <- training_raw[-inTrain,]

    # Построить glm модель на выборке для обучения
fit <- train(factor(classe) ~ ., data=training[, -c(1,3:7)], method="rpart")
# wtf! Не предсказывает исход D    
    # Проверить на тестовой
pred <- predict(fit, newdata=testing)

    # Попробобвать rf и gbm  

    # Попробовать комбинированную модель

    # Выбрать итоговую модель

    # Определить параметры оценки качества модели по материала для лекций

    # Прогнать разбивку, построение модели и оценку параметров качества 10 раз

    # Усреднить для того, чтобы повысить точность оценки качества на тестовой выборке.

# Построить модель с использованием идентификтаора пользователя как фактор и без него.
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
